# Generated by Django 2.2.1 on 2019-05-10 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('channel_id', models.CharField(max_length=9, unique=True)),
                ('channel_name', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date(2019, 5, 15))),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=9, unique=True)),
                ('slack_username', models.CharField(max_length=32, unique=True)),
                ('slack_name', models.CharField(max_length=128)),
                ('intro', models.TextField(blank=True)),
                ('available', models.BooleanField(default=False)),
                ('can_be_excluded', models.BooleanField(default=False)),
                ('pools', models.ManyToManyField(blank=True, to='matcher.Pool')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met', models.BooleanField(default=False)),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matcher.Person')),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matcher.Person')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.Round')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
    ]
