# Generated by Django 2.2.1 on 2019-05-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='slack_user_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='slack_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='person',
            name='slack_name',
        ),
        migrations.AddField(
            model_name='person',
            name='given_name',
            field=models.CharField(default='Harrison', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='Liddiard', max_length=64),
            preserve_default=False,
        ),
    ]
